import Link from "next/link";
import { PageHeader } from "@/components/admin/page-header";
import { KpiCard } from "@/components/admin/kpi-card";
import { DataTable } from "@/components/admin/data-table";
import  PaymentStatusBadge from "@/components/ui/badge";
import {Award, CheckCircle, Users, Wallet} from "lucide-react"
import {db} from "@/lib/db";
import {eq, sql,and, isNotNull} from "drizzle-orm";
import {streams, users, payments, accessGrants} from "@/lib/db/schema";
import { StudentsCreatePanel } from "@/components/college-admin/students-create-panel";
import { requireCollegeAdmin } from "@/lib/college-admin/actions";
import  StudentsAddForm  from "@/components/college-admin/student-add-form";
import {REPORT_PRICE_PAISE} from "@/lib/constants";

export const dynamic = "force-dynamic";

export default async function CollegeAdminOverviewPage() {
  const me = await requireCollegeAdmin();

  const allStreams = await db.select({id: streams.id, name: streams.name}).from(streams);
  const grantsSubquery = db.select({
    userId: accessGrants.userId,
    totalGrants: sql<number>`COUNT(*)`.as("total_grants"),
    availableGrants: sql<number>`COUNT(*) FILTER (WHERE ${accessGrants.usedForAssessmentId} IS NULL)`.as("available_grants"),
    })
    .from(accessGrants)
    .groupBy(accessGrants.userId)
    .as("grants_summary");

  const allStudents = await db
  .select({id: users.id, name: users.name, email: users.email, streamName: streams.name, phone: users.phone, availableGrants: sql<number>`COALESCE(${grantsSubquery.availableGrants}, 0)`}).from(users)
  .leftJoin(grantsSubquery, eq(users.id, grantsSubquery.userId))
  .leftJoin(streams, eq(users.streamId, streams.id))
  .where(eq(users.createdBy, me));

  const totalGrants = await db
  .select({count: sql<number>`COUNT(*)`}).from(accessGrants)
  .leftJoin(users, eq(accessGrants.userId, users.id))
  .where(eq(users.createdBy, me));
  const consumedGrants = await db
  .select({count: sql<number>`COUNT(*)`}).from(accessGrants)
  .leftJoin(users, eq(accessGrants.userId, users.id))
  .where(and(eq(users.createdBy, me), isNotNull(accessGrants.usedForAssessmentId)));

  return (
    <>
      <PageHeader
        title="College Admin Dashboard"
        description="Welcome to your dashboard! Here you can manage your college's profile."
        actions={<StudentsCreatePanel streams={allStreams} />}
      />

      <section className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3 sm:gap-4">
        <KpiCard
          label="Total Students"
          value={allStudents.length}
          icon={Users}
          hint="Number of students"
        />
        <KpiCard
          label="Total grants"
          value={totalGrants[0]?.count ?? 0}
          icon={Award}
          hint="Total grants issued till now"
        />
        <KpiCard
          label="Grants consumed"
          value={consumedGrants[0]?.count ?? 0}
          icon={CheckCircle}
          hint="Reports generated by students"
        />
        <KpiCard
          label="Total money spent"
          value={totalGrants[0]?.count ? `₹${totalGrants[0].count * Number(REPORT_PRICE_PAISE) / 100}` : "₹0"}
          icon={Wallet}
          hint="Money spent to buy grants"
        />
      </section>

      <section className="grid grid-cols-1 md:grid-cols-4 gap-3 sm:gap-4 mt-5 sm:mt-6 md:mt-8">
        <div className="md:col-span-3">
        <h2 className="font-display font-bold text-base sm:text-lg text-ink mb-3">Recently Added Students</h2>
        <DataTable
          rows={allStudents.map((s, i) => ({ id: String(i), email: s.email, name: s.name, streamName: s.streamName, phone: s.phone, availableGrants: s.availableGrants }))}
          emptyText = "No students added yet"
          columns={[
            {key: "name", header: "Name", 
            render: r => <div className="font-medium text-ink flex flex-col gap-0.5"><div>{r.name}</div><div className="text-sm text-ink-soft">{r.email}</div></div>},
            {key: "streamName", header: "Stream", render: r => <div className="font-medium text-ink">{r.streamName}</div>},
            {key: "phone", header: "Phone", render: r => <div className="font-medium text-ink">{r.phone}</div>},
            {key: "availableGrants", header: "Grants", render: r => <span className={`font-semibold ${r.availableGrants > 0 ? 'text-green-500' : 'text-red-500'}`}>{r.availableGrants}</span>}
          ]}
          />
        </div>
        <div className="md:col-span-1">
        <h2 className="font-display font-bold text-base sm:text-lg text-ink mb-3">Add student</h2>
        <StudentsAddForm streams={allStreams} />
        </div>
        </section>
    </>
    )
}